CREATE TABLE IF NOT EXISTS general_config (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    key   VARCHAR(50)  NOT NULL UNIQUE,
    value VARCHAR(500) NOT NULL,
    updated_at_epoch_ms BIGINT NOT NULL
);
